### ISSUE TITLE
Sass::SyntaxError in ActiveAdmin::Devise::Sessions#new

### ISSUE THREAD

**Issue by imidsac** [activeadmin/activeadmin#4248]
ActionView::Template::Error (Undefined mixin 'box-shadow'.):
     6:   <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>
     7: 
     8:   <% ActiveAdmin.application.stylesheets.each do |style, options| %>
     9:     <%= stylesheet_link_tag style, options %>
    10:   <% end %>
    11:   <% ActiveAdmin.application.javascripts.each do |path| %>
    12:     <%= javascript_include_tag path %>

**Comment by seanlinsley** [comment]
We don't use a `box-shadow` mixin on master. What version of Active Admin are you using? Can you provide a full stack trace?

**Comment by seanlinsley** [comment]
It looks like this was fixed by #1913 back in 2013. If you upgrade Active Admin, the problem will go away.

**Comment by DevilalDheer** [comment]
This issue is not fixed, Please re-open this issue.

ActionView::Template::Error (Undefined mixin 'box-shadow'.):
     6:   <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>
     7: 
     8:   <% ActiveAdmin.application.stylesheets.each do |style, options| %>
     9:     <%= stylesheet_link_tag style, options %>
    10:   <% end %>
    11:   <% ActiveAdmin.application.javascripts.each do |path| %>
    12:     <%= javascript_include_tag path %>
  active_admin_editor (1.1.0) app/assets/stylesheets/active_admin/editor.css.scss:25:in `box-shadow'
  active_admin_editor (1.1.0) app/assets/stylesheets/active_admin/editor.css.scss:25

**Comment by seanlinsley** [comment]
That's coming from the active_admin_editor gem. It looks like that has been fixed on the master branch of that gem, but it hasn't been released to Rubygems: https://github.com/ejholmes/active_admin_editor/commit/0cae244c38b054bba86277f0b2f6d499d79869a7

**Comment by fro** [comment]
Hi @seanlinsley,

I have the same issue here. I'm trying to update a Rails app 3.1.10 to 3.2.22.2 with the same activeadmin version 0.4.3 if possible.

I have tried to create a fresh Rails 3.2.22.2 install with activeadmin 0.4.3, 0.4.4, 0.5.0... but the error pop everytime:

    Sass::SyntaxError in Active_admin/devise/sessions#new
    Undefined mixin 'box-shadow'.
    (in /Library/WebServer/Documents/boudiou/app/assets/stylesheets/active_admin.css.scss)

Here's the full trace: https://gist.github.com/fro/e56f9112c7fcba4a79cb

My Gemfile:

```
source 'https://rubygems.org'
    gem 'rails', '3.2.22.2'
    gem 'sqlite3'
    group :assets do
      gem 'sass-rails',   '~> 3.2.3'
      gem 'coffee-rails', '~> 3.2.1'
      gem 'uglifier', '>= 1.0.3'
    end
    gem 'jquery-rails'
    gem 'pg'
    gem 'devise'
    gem 'activeadmin', '0.4.3'
    gem 'formtastic', '2.0.2'
```

The full gem list:
```
actionmailer (3.2.22.2)
actionpack (3.2.22.2)
activeadmin (0.4.3)
activemodel (3.2.22.2)
activerecord (3.2.22.2)
activeresource (3.2.22.2)
activesupport (3.2.22.2)
arbre (1.0.3)
arel (3.0.3)
bcrypt (3.1.11)
bigdecimal (1.2.6)
bourbon (4.2.6)
builder (3.0.4)
bundler (1.11.2)
coffee-rails (3.2.2)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
devise (3.5.6)
erubis (2.7.0)
execjs (2.6.0)
fastercsv (1.5.5)
formtastic (2.0.2)
has_scope (0.6.0)
hike (1.2.3)
i18n (0.7.0)
inherited_resources (1.6.0)
io-console (0.4.3)
journey (1.0.4)
jquery-rails (3.1.4)
json (1.8.3, 1.8.1)
kaminari (0.16.3)
mail (2.5.4)
meta_search (1.1.3)
mime-types (1.25.1)
minitest (5.4.3)
multi_json (1.11.2)
orm_adapter (0.5.0)
pg (0.18.4)
polyamorous (0.5.0)
polyglot (0.3.5)
power_assert (0.2.2)
psych (2.0.8)
rack (1.4.7)
rack-cache (1.6.1)
rack-ssl (1.3.4)
rack-test (0.6.3)
rails (3.2.22.2)
railties (3.2.22.2)
rake (11.1.1, 10.4.2)
rdoc (4.2.0, 3.12.2)
responders (1.1.2)
sass (3.4.21)
sass-rails (3.2.6)
sprockets (2.2.3)
sqlite3 (1.3.11)
test-unit (3.0.8)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
treetop (1.4.15)
tzinfo (0.3.47)
uglifier (2.7.2)
warden (1.2.6)
```

I've spend 1 full day of testing, looking at stackoverflow solutions... but nothing's working.
Any ideas?

**Comment by timoschilling** [comment]
@fro you need Bourbon < 3.1.0

**Comment by fro** [comment]
@timoschilling Wow, thank you so much.

Here's what I've changed in my Gemfile:
```
gem 'jquery-rails', '~> 2.3.0'
gem 'bourbon', '3.0.1'
```

**Comment by ekumachidi** [comment]
to fix that issue, use this in your gem file

gem 'active_admin_editor', github: 'ejholmes/active_admin_editor'

in place of
gem 'active_admin_editor'
