### ISSUE TITLE
Compatible activeadmin version for rails 5.0.0

### ISSUE THREAD

**Issue by Aywac** [activeadmin/activeadmin#4506]
Hi
I installed rails version 5.0.0 just now, but i found out that the last pre release of activeadmin is not compatible with it.
Here what i get when i run bundle update :

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.0.0) x86-mingw32

activeadmin (~> 1.0.0.pre3) x86-mingw32 was resolved to 1.0.0.pre3, which
depends on
      rails (< 5.0, >= 3.2) x86-mingw32

It was worked with the rails 5.0.0.rc1 without any problem before i update the rails to the last version.

**Comment by alagos** [comment]
Same problem here
```
$ bundle update rails
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies............
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (< 5.1, >= 5.0.0)

    activeadmin was resolved to 1.0.0.pre2, which depends on
      rails (< 5.0, >= 3.2)
```

**Comment by timoschilling** [comment]
should be fixed with 1.0.0.pre4

**Comment by Aywac** [comment]
@timoschilling The problem still exist with activeadmin dependencies.
Activeadmin depends on inherited_resources (~> 1.6) which depends on railties (< 5, >= 3.2) and actionpack (< 5, >= 3.2)
And the last existed inherited_resources gem is 1.6.0 :/

**Comment by timoschilling** [comment]
No, thats a other problem.

**Comment by timoschilling** [comment]
can you try this:
```ruby
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
```

**Comment by Aywac** [comment]
The forked inherited_resources gem depends on an old has_scope gem (~> 0.6.0.rc) which depends on actionpack (< 5, >= 3.2) and activesupport (< 5, >= 3.2)
Maybe the problem will be fixed If has_scope (~> 0.6.0.rc) replaced with the 0.7.0 version.

**Comment by timoschilling** [comment]
please retry

**Comment by Aywac** [comment]
Now it's working. Thanks!!

**Comment by timoschilling** [comment]
please 👍 this PR https://github.com/josevalim/inherited_resources/pull/411
