### ISSUE TITLE
NoMethodError in Admin::[Model Name]#index undefined method `klass' for nil:NilClass 

### ISSUE THREAD

**Issue by lgm1213** [activeadmin/activeadmin#5197]
I have been receiving the error below in two models when clicked on the navbar. I have checked on similar issues but there seems to be no resolution or the issues get closed without the resolution being published. The issue previously opened leans towards an association issue, but was not ceratin due to closure. [](https://github.com/activeadmin/activeadmin/issues/4470)

```
NoMethodError in Admin::Buildings#index
undefined method `klass' for nil:NilClass

def source_reflection
  through_reflection.klass._reflect_on_association(source_reflection_name)
end

activerecord (5.1.4) lib/active_record/reflection.rb:796:in `source_reflection'
activerecord (5.1.4) lib/active_record/reflection.rb:987:in `collect_join_reflections'
activerecord (5.1.4) lib/active_record/reflection.rb:833:in `collect_join_chain'
activerecord (5.1.4) lib/active_record/reflection.rb:275:in `chain'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:129:in `block in default_association_filters'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:129:in `reject!'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:129:in `default_association_filters'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:109:in `default_filters'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:94:in `filter_lookup'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:23:in `filters'
activeadmin (1.1.0) lib/active_admin/filters/resource_extension.rb:143:in `block in filters_sidebar_section'
activeadmin (1.1.0) lib/active_admin/helpers/optional_display.rb:25:in `instance_exec'
activeadmin (1.1.0) lib/active_admin/helpers/optional_display.rb:25:in `display_on?'
activeadmin (1.1.0) lib/active_admin/resource/sidebars.rb:17:in `block in sidebar_sections_for'
activeadmin (1.1.0) lib/active_admin/resource/sidebars.rb:17:in `select'
activeadmin (1.1.0) lib/active_admin/resource/sidebars.rb:17:in `sidebar_sections_for'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:114:in `sidebar_sections_for_action'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:138:in `skip_sidebar?'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:76:in `build_page_content'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:50:in `block in build_page'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:49:in `build_page'
activeadmin (1.1.0) lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (1.1.0) app/views/active_admin/resource/index.html.arb:2:in `block in __home_luis__rbenv_versions_______lib_ruby_gems_______gems_activeadmin_______app_views_active_admin_resource_index_html_arb___1200245893402742600_69935971191560'
arbre (1.1.1) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.1.1) lib/arbre/context.rb:45:in `initialize'
activeadmin (1.1.0) app/views/active_admin/resource/index.html.arb:1:in `new'
activeadmin (1.1.0) app/views/active_admin/resource/index.html.arb:1:in `__home_luis__rbenv_versions_______lib_ruby_gems_______gems_activeadmin_______app_views_active_admin_resource_index_html_arb___1200245893402742600_69935971191560'
actionview (5.1.4) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.4) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.4) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.4) lib/action_view/template.rb:155:in `render'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
actionview (5.1.4) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.4) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.4) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.4) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.4) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.4) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.4) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.4) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.4) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/luis/.rbenv/versions/2.4.1/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:43:in `render'
responders (2.4.0) lib/action_controller/responder.rb:238:in `default_render'
responders (2.4.0) lib/action_controller/responder.rb:170:in `to_html'
responders (2.4.0) lib/responders/flash_responder.rb:107:in `to_html'
responders (2.4.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.4.0) lib/action_controller/responder.rb:156:in `call'
responders (2.4.0) lib/action_controller/respond_with.rb:211:in `respond_with'
inherited_resources (1.7.2) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (1.1.0) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by varyonic** [comment]
If you can reproduce in a [bug report](https://github.com/activeadmin/activeadmin/blob/master/lib/bug_report_templates/active_admin_master.rb) that will increase the likelihood of an earlier resolution, thanks.

**Comment by ragarwa7** [comment]
Are we able to find a fix for this issue?

**Comment by ragarwa7** [comment]
This issue is specific to activeadmin version 1.1.0. 
The issue is resolved when I switched back to version 1.0.0.

**Comment by klapperkopp** [comment]
I am still having this issue. For it comes up when I try to access the `User` model in the ActiveAdmin Interface. I could narrow it down to a single `has_many :xxx, through: :yyy` declaration. If I deactivate that, it will work.
Funny thing is, I have some other has_many, through associations in that User model and they seem to work.

**Comment by raphox** [comment]
https://github.com/activerecord-hackery/ransack/issues/1063

**Comment by andriytyurnikov** [comment]
any solutions?

**Comment by raphox** [comment]
hi @andriytyurnikov 
I created the file `config/initializers/ransack/nodes_bindable.rb` with this content:
```ruby
module Ransack::Nodes::Bindable
  def bound?
    attr_name.present? && parent.to_s.present?
  end
end
```
