### ISSUE TITLE
Rails 6.0.0.RC2  - wrong number of arguments (given 3, expected 4)

### ISSUE THREAD

**Issue by cdesch** [activeadmin/activeadmin#5821]
Rails 6.0.0.RC2 has breaking change which makes rendering the index for a resource throw an error. I backed out Rails RC2 for RC1 and it resolves the issue. 

### Expected behavior

Render index page of the resource. e.g. `/admin/transactions`

### Actual behavior

Receive error below for this initializer: 

[def initialize(base, table, associations, join_type)](https://github.com/rails/rails/blob/2e9176c04a9e167efc15f904fd52ab793a29b931/activerecord/lib/active_record/associations/join_dependency.rb#L67)

```
Started GET "/admin/rewards" for 127.0.0.1 at 2019-07-27 15:18:00 -0400
   (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Admin::RewardsController#index as HTML
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 15], ["LIMIT", 1]]
Completed 500 Internal Server Error in 91ms (ActiveRecord: 8.5ms | Allocations: 34780)
  
ArgumentError (wrong number of arguments (given 3, expected 4)):
  
activerecord (6.0.0.rc2) lib/active_record/associations/join_dependency.rb:67:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:264:in `new'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:264:in `build_joins'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:219:in `join_dependency'
ransack (2.1.1) lib/ransack/adapters/active_record/ransack/context.rb:27:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/context.rb:10:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/ransack/context.rb:11:in `new'
ransack (2.1.1) lib/ransack/adapters/active_record/ransack/context.rb:11:in `for_class'
ransack (2.1.1) lib/ransack/context.rb:22:in `for'
ransack (2.1.1) lib/ransack/search.rb:25:in `initialize'
ransack (2.1.1) lib/ransack/adapters/active_record/base.rb:18:in `new'
ransack (2.1.1) lib/ransack/adapters/active_record/base.rb:18:in `ransack'
activerecord (6.0.0.rc2) lib/active_record/relation/delegation.rb:106:in `public_send'
activerecord (6.0.0.rc2) lib/active_record/relation/delegation.rb:106:in `block in method_missing'
activerecord (6.0.0.rc2) lib/active_record/relation.rb:398:in `block in scoping'
activerecord (6.0.0.rc2) lib/active_record/relation.rb:772:in `_scoping'
activerecord (6.0.0.rc2) lib/active_record/relation.rb:398:in `scoping'
activerecord (6.0.0.rc2) lib/active_record/relation/delegation.rb:106:in `method_missing'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:217:in `apply_filtering'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:59:in `block in find_collection'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:58:in `each'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:58:in `find_collection'
activeadmin (2.2.0) lib/active_admin/resource_controller/data_access.rb:44:in `collection'
inherited_resources (1.10.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (2.2.0) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (6.0.0.rc2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0.rc2) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0.rc2) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0.rc2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0.rc2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0.rc2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0.rc2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0.rc2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0.rc2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0.rc2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.0.rc2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0.rc2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0.rc2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0.rc2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0.rc2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0.rc2) lib/action_dispatch/routing/route_set.rb:837:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/cookies.rb:644:in `call'
activerecord (6.0.0.rc2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
rollbar (2.20.2) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
rollbar (2.20.2) lib/rollbar.rb:145:in `scoped'
rollbar (2.20.2) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
rollbar (2.20.2) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
web-console (4.0.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.0) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0.rc2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0.rc2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0.rc2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0.rc2) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.0.6) lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.0.rc2) lib/rails/engine.rb:526:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```
### How to reproduce

Run ActiveAdmin 2.2.0 and Rails 6.0.0.RC2

**Comment by mjbamford** [comment]
Looks to be fixed on master b5495dd

**Comment by rickychilcott** [comment]
I'm running into this as well -- upgrading to master doesn't actually fix the issue.  I've confirmed I am using the latest Ransack (2.1.1) which also claims to be Rails 6.0.0.rc2 compatible https://github.com/activerecord-hackery/ransack/commit/2c9da3a1139d536fdbc28414c4c913560ba7798b

Based on the backtrace it does seem to be a Ransack issue, but I'm not sure.

**Comment by rickychilcott** [comment]
Thanks @mjbamford.

You can work around this issue for now by adding the following to your Gemfile.

`gem "ransack", github: "activerecord-hackery/ransack", ref: "aada8"`

then run `bundle update ransack`

**Comment by deivid-rodriguez** [comment]
Yes!

You can fix the issue for now by pointing to ransack master. Or even better, to a specific sha reference where the issue is fixed as @rickychilcott suggested :smile:.

I [requested a ransack release](https://github.com/activerecord-hackery/ransack/issues/1032#issuecomment-516373642) that supports rails 6.0.0.rc2, but I'm not sure whether that will happen or not.

I'll leave this opened for visibility of the workaround until a new ransack release is cut.

**Comment by puskuruk** [comment]
First, I made @rickychilcott 's suggestion on my own computer after that I need work with my girlfriend's laptop and in my girlfriend's computer I still get the error 'wrong number of arguments (given 4, expected 3)' which was solved on my own computer.

Our project use Rails 6.0.0.RC2 too...

**Comment by MarcoBomfim** [comment]
Seeing this yesterday as well from a brand new project. The only way I was actually able to get pass this, was by including @rickychilcott 's gem, before running `bundle install` on the new project. The 'hacked' ransack was then installed, and it worked properly. 

I work on another project that is using Rails 6 RC1, and this does not happen in there. Is it really fixed on master, as @mjbamford mentioned?

**Comment by rickychilcott** [comment]
To clarify, this isn't my gem, just a sha that includes the patch from ransack. Yes, Ransack master does have it fixed, but I would suggest pinning it at a specific sha so that it doesn't inadvertantly break if Ransack master gets new API changes that break ActiveAdmin in other ways.

@deivid-rodriguez isn't getting a positive reception with cutting a prerelease version of the Ransack gem, so for now my workaround is what we'll have to do. Also, yes, when Rails 6 RC1 is used, you get a different version of the Ransack gem which is fine with AA.

It's strange. Even though we're in Rails 6 rc2, if feels like the whole community is sluggish to get to a Rails 6.0 release. Maybe it's just summer and we'll be trucking along here in a few more weeks. Thanks for everyone's work on this!

**Comment by juampi** [comment]
[Ransack v2.30 has been released](https://github.com/activerecord-hackery/ransack/releases/tag/v2.3.0), which includes a fix for this issue.

**Comment by juampi** [comment]
[Ransack v2.3.0 has been released](https://github.com/activerecord-hackery/ransack/releases/tag/v2.3.0), which includes a fix for this issue.

**Comment by rickychilcott** [comment]
This is fixed on master now without the need to manually managing ransack's version in the project. Thanks @javierjulio and @deivid-rodriguez!

You should be able to close this issue.

**Comment by javierjulio** [comment]
Thanks!

**Comment by franzejr** [comment]
Is this in the latest release ?

**Comment by deivid-rodriguez** [comment]
Hi @franzejr, sorry I didn't reply earlier. You need at least ransack 2.3.0 to pick up this bug fix.
