### ISSUE TITLE
On install : the asset "active_admin.css" is not present in the asset pipeline.

### ISSUE THREAD

**Issue by Andrew-Max** [activeadmin/activeadmin#6007]
### Did you find a bug?
On a fresh install with rails 6 and rails-sass no assets get installed and going to '/admin' results in an error: The asset "active_admin.css" is not present in the asset pipeline.

### Expected behavior
Should go to a login screen

### Actual behavior
An error is thrown

### How to reproduce
Fresh install according to the guide's 'Installation' section

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by Andrew-Max** [comment]
It looks like this is solved by `rails generate active_admin:assets` but it is worth noting that the documentation does not instruct the user to ever run this command on a fresh install.

**Comment by guilpejon** [comment]
In my case that command did not solved the error because I already had the files `app/assets/javascripts/active_admin.js` and `app/assets/stylesheets/active_admin.scss`.
Anyone else having this problem? I'm thinking it has something to do with the fact that Rails 6 uses webpack by default, but the assets are generated on `app/assets`.

**Comment by deivid-rodriguez** [comment]
I think you're supposed to use `sassc-rails` instead of `sass-rails`, maybe that's the issue?

**Comment by deivid-rodriguez** [comment]
Actually scratch that since I just realized that `sass-rails` is just a wrapper around `sassc-rails`. `rails generate active_admin:install` should run `rails generate active_admin:assets` so I don't know what's going on here. I also tried to reproduce this, but everything worked correctly.

Could you share some steps to reproduce this?

**Comment by Arugin** [comment]
Upgraded from rails 4 to rails 6, In the development envirobment everything works ok. In the production has the same error.

**Comment by deivid-rodriguez** [comment]
Could you share some steps to reproduce this?

**Comment by mrtomhoward** [comment]
@Arugin and others still experiencing this problem.

I had this issue today with an app that was initially built in Rails 5 and that I recently updated to Rails 6.  

What fixed it for me was running `rails app:update` (and manually reviewing all the environment and initializer files as some are updated or overwritten by the update procedure).

I hadn't done that before now; I'd just updated the Rails Gem.

After doing that, Active Admin loads without any problems.

With my install, the updated `config/application.rb` had this line commented out:
`#require "sprockets/railtie"`

 ...which is the Rails 6 way of disabling the asset pipeline (and which suits me fine as this app is API-only apart from ActiveAdmin).

But I tried loading the api wth `require "sprockets/railtie` uncommented, and it works fine that way too.

**Comment by oyenmwen** [comment]
This problem occurs with Rails 6 apps as they use Webpacker as the default asset generator. You need to explicitly configure activeadmin to use webpacker.

at active_admin installation:
run `rails g active_admin:install --use_webpacker`

If already installed:

add  `config.use_webpacker = true`  at  `config/initializers/active_admin.rb`
and then run `rails g active_admin:webpacker`

**Comment by francoserio** [comment]
> This problem can occur with Rails 6 apps as they use Webpacker as the default asset generator. You need to explicitly configure activeadmin to use webpacker.
> 
> at active_admin installation:
> run `rails g active_admin:install --use_webpacker`
> 
> If already installed:
> 
> add `config.use_webpacker = true` at `config/initializers/active_admin.rb`
> and then run `rails g active_admin:webpacker`
> 
> Source: https://activeadmin.info/0-installation.html#setting-up-active-admin

Thanks! This fixed the issue for me!

**Comment by mmell** [comment]
This happened to me on a fresh Rails 6 site. It only manifested in the production deployment.

**Comment by Zidail** [comment]
Seems like I'm having the same issue with a fresh install of Active Admin.
It works in development but doesn't in production. 
Doesn't seem like webpacker picked up the scss file.

Followed the instructions in: https://activeadmin.info/0-installation.html#setting-up-active-admin

**Comment by mmell** [comment]
Setting `RAILS_SERVE_STATIC_FILES=1` in the production environment solved it for me.

**Comment by uzzybotak** [comment]
In case someone still having the same issues after trying all the solutions already written above. I opened the config/webpacker.yml and change this line:
`
default: &default
  ...
  extract_css: true
  ...
`

Somehow, my app wants to have the webpacker to also emit the css for the active_admin.css to be identified. Hopefully it will help someone here

**Comment by thisismydesign** [comment]
Happens when there's no `app/assets` folder, e.g. for api-only apps. Fix by creating the folder or `rails generate active_admin:assets`
