### ISSUE TITLE
Filter select show object instead of object name

### ISSUE THREAD

**Issue by Shpigford** [activeadmin/activeadmin#728]
As you can see from the example below, certain filter `<select>` dropdowns show the object as opposed to the object's name.

So how would I customize what field is used for the representation of the record in the drop down?

![Example](https://img.skitch.com/20111106-pcx14qqbqqjt8313x4m616crha.png)

**Comment by reneweteling** [comment]
Well.... the way i fixed is is by applying the member value
filter :project, member_label: proc{|a| a.to_s}

**Comment by pmaclin** [comment]
Working with 1.0.0. pre5 and the issue persists as described. Only object shows on filter for my User model but column shows as expected. Working w/Devise. Not sure where to make the adjustment.
ruby 2.3.1
rails 4.2.5.2
